// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC940xkhBLneZ9H2xTd_EG4M-9DNPKsX4Y',
    appId: '1:106999809537:android:9d19c364f18116d36d2200',
    messagingSenderId: '106999809537',
    projectId: 'dodiddone-43bc8',
    storageBucket: 'dodiddone-43bc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRS1msPDooQ_CXyS2ncmZmEFYbdm_Y6P0',
    appId: '1:106999809537:ios:82bc97483ac1d2b56d2200',
    messagingSenderId: '106999809537',
    projectId: 'dodiddone-43bc8',
    storageBucket: 'dodiddone-43bc8.appspot.com',
    iosBundleId: 'com.example.zcDodiddone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQlwWQIQlubKyYpR8GvVdJwCoPFOAcyQ',
    appId: '1:106999809537:web:8dbcfeec7e882e2a6d2200',
    messagingSenderId: '106999809537',
    projectId: 'dodiddone-43bc8',
    authDomain: 'dodiddone-43bc8.firebaseapp.com',
    storageBucket: 'dodiddone-43bc8.appspot.com',
    measurementId: 'G-NWPHGLY6ZM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuQlwWQIQlubKyYpR8GvVdJwCoPFOAcyQ',
    appId: '1:106999809537:web:672bf48a268f2c9a6d2200',
    messagingSenderId: '106999809537',
    projectId: 'dodiddone-43bc8',
    authDomain: 'dodiddone-43bc8.firebaseapp.com',
    storageBucket: 'dodiddone-43bc8.appspot.com',
    measurementId: 'G-CB1HJRL8TG',
  );

}